kind: Service
apiVersion: v1
metadata:
  name: {{ template "mlrun-kit.jupyter.fullname" . }}
  labels:
    app.kubernetes.io/component: jupyter-notebook
    app.kubernetes.io/name: {{ template "mlrun-kit.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}

spec:
{{- if .Values.jupyterNotebook.service.nodePort }}
  type: NodePort
{{- end }}
  selector:
    app.kubernetes.io/component: jupyter-notebook
    app.kubernetes.io/name: {{ template "mlrun-kit.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - name: admin
    protocol: TCP
    port: 8888
    targetPort: 8888
{{- if .Values.jupyterNotebook.service.nodePort }}
    nodePort: {{ .Values.jupyterNotebook.service.nodePort }}
{{- end }}
